---
- hosts: all
  vars:
          - userdb:
                  - name: "a1"
                    password: "a1_pass"
                    group: "a1_group"
                  - name: "a2"
                    password: "a2_pass"
                    group: "a2_group"
  tasks:
          - user:
                  name: "{{ item.name }}"
                  password: "{{ item.password }}"
                  group: "{{ item.group }}"
            loop: "{{ userdb }}"
