---
- hosts: all
  vars:
          - x:
                  - "httpd"
                  - "php"
  tasks:
          - package:
                  name: "{{ item  }}"
                  state: present
            loop: "{{ x }}"
