---
- hosts: localhost
  tasks:
          - name: Sending an e-mail using Gmail SMTP servers
            mail:
                    host: smtp.gmail.com
                    port: 587
                    username:   
                    password: 
                    to: 
                    subject: Ansible-report
                    body: System {{ ansible_hostname }} has been successfully provisioned.

