---
- hosts: all
  tasks:
          - package:
                  name: "httpd"
                  state: present
          - template:
                  dest: "/etc/httpd/conf.d/lw.conf"
                  src: "lw.conf"
          - file:
                  state: "directory"
                  path: "/var/www/lw"
          - copy:
                  src: "index.html"
                  dest: "/var/www/lw"
          - service:
                  name: "httpd"
                  state: "restarted"
                  enabled: yes
          - service:
                  name: "firewalld"
                  state: "started"
                  enabled: yes
          - firewalld:
                  port: "80/tcp"
                  state: enabled
                  permanent: yes
                  immediate: yes
          - firewalld:
                  port: "8080/tcp"
                  state: enabled
                  permanent: yes
                  immediate: yes
