---
- hosts: all
  tasks:
          - file:
                  state: directory
                  path: "/redhat_iso_dir"
          - mount:
                  src: "/dev/cdrom"
                  path: "/redhat_iso_dir"
                  state: "mounted"
                  fstype: "iso9660"
          - yum_repository:
                  name: "BASEOS"
                  description: "Adding baseos repository"
                  file: redhat_iso
                  baseurl: file:///redhat_iso_dir/BaseOS
                  gpgcheck: no
          - yum_repository:
                  name: "APPSTREAM"
                  description: "Adding appstream repository"
                  file: redhat_iso
                  baseurl: file:///redhat_iso_dir/AppStream
                  gpgcheck: no
          - package:
                  name: "httpd"
                  state: "present"
          - copy:
                  dest: "/var/www/html/index.html"
                  content: "THIS IS TESTING WEBSITE"
          - service:
                  name: "httpd"
                  state: "started"
                  enabled: yes
          - service:
                  name: "firewalld"
                  state: "started"
                  enabled: yes
          - firewalld:
                  port: "80/tcp"
                  state: enabled
                  permanent: yes
                  immediate: yes
